apiVersion: v1
kind: Service
metadata:
  labels:
    app: mirror-service
  name: mirror-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mirror-frontend
