apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mirror-ingress
  namespace: dev-mirror
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - admin'

spec:
  rules:
  - host: dev.mirror.tino.sh
    http:
      paths:
      - backend:
          serviceName: mirror-service
          servicePort: 8080

  tls:
  - hosts:
    - dev.mirror.tino.sh
    secretName: dev-mirror-tino-sh-tls
