apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev-mirror 
  name: mirror-pvc-modules
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev-mirror
  name: mirror-pvc-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
